### PR TITLE
Dropped vertically centered div, but when content overflows, it shoul...

### PR DESCRIPTION
**Pull request by jtm13**
…d be at the top

### Description

The login and signup no longer center vertically. However, when they overflow, they appear right below the sticky header instead of halfway through.

Typically this will be a summary of your ticket.

### What are you changing?

- Shawn's change.

### Did you increase testing or code coverage?

NO

### Did you add any dependencies to the project?

NO

### Did you update the relevant documentation?

NO, since it was just visual changes.

### CODE REVIEW

**Comment by jtm13** [comment]
Also added the right colors. Edited the `tailwind.config.js` file to make it to where we can use an alias (primary) for the main color for the site. I did it so that we can use the tailwind classes while not having to change multiple files multiple times for just a main color change again.

**Comment by shawnpradeep** [comment]
Can we have the content all fit within the viewport? 

i.e.
image

image

**Comment by jtm13** [comment]
Do you want it to fit with all viewports? Like mobile and desktop? If so, would readability be a problem?

**Comment by shawnpradeep** [comment]
for now, let's just stick to desktop. we can implement mobile down the line

**Review by dhruv2253 — APPROVED** [review]

**Pull request merged**
