### PR TITLE
Feature/profile

### PR DESCRIPTION
**Pull request by jtm13**
Added Profile to site.
Issue #16 
Want to know other's thoughts on the design.

### CODE REVIEW

**Comment by genki-aik** [comment]
I will get the design reviewed by Aniyah

**Comment by genki-aik** [comment]
Lets hold off on the QR code until next release which will be next week

**Comment by genki-aik** [comment]
What to include:
Name
Email
School
Interests
Teammates
Schedule Builder
Quicklinks

**Comment by genki-aik** [comment]
Hold this feature off until next week, this will not be included in Version 1 of mybyte

**Comment by jtm13** [comment]
> What to include: Name Email School Interests Teammates Schedule Builder Quicklinks

For the Interests, where is that stored in firebase? Also, it might be helpful to pin the firebase document structures in the discord. Then we can modify `AuthContext` to get what we want.
For the Schedule Builder, is it just a place where people can add predefined events?

**Comment by jtm13** [comment]
Added QR Code functionality. Also added package `qrcode` to make the QR Code.

**Pull request merged**
